#!/usr/bin/env bash
# Prints a short orientation block at the start of a Claude Code session.
# Wired up as a SessionStart hook in .claude/settings.json.
#
# Read-only and cheap by design — it must never modify the tree, and it must
# finish fast enough that nobody notices it ran.

set -uo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 0

branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')
dirty=$(git status --porcelain 2>/dev/null | wc -l | tr -d ' ')

if bash tool/codemap.sh --check >/dev/null 2>&1; then
  map="current"
else
  map="STALE — run: bash tool/codemap.sh"
fi

cat <<BRIEF
Yello project brief (auto-generated by tool/session_brief.sh)

  Branch: $branch ($dirty uncommitted file(s)) · Code map: $map

  Read in this order before touching code — the answer is usually already
  written down, so don't grep 220 Dart files to re-derive it:
    1. docs/ARCHITECTURE.md  layers, request lifecycle, where new code goes
    2. docs/CODEMAP.md       generated index: files, routes, DI registrations
    3. docs/GOTCHAS.md       what already broke on-device (read before UI work)
    4. docs/BACKEND.md       endpoints, envelope, permanent gaps
    5. docs/DECISIONS.md     why it is this way

  Full rules: AGENTS.md (shared) and CLAUDE.md (Claude-specific).
  After the change: bash tool/codemap.sh if files/routes/DI moved, and a
  CHANGELOG.md entry under [Unreleased] if it is user-visible.
BRIEF
